import React, { useRef, useState } from "react";
import { Swiper, SwiperSlide, useSwiper } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/free-mode";
import "swiper/css/scrollbar";
import { Mousewheel } from 'swiper';
import { FreeMode } from "swiper";
import { Scrollbar } from "swiper";
import { Pagination } from "swiper";




import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Nab from "../components/parts/Nab";
import Banner from "../components/parts/hero";
import About from "../components/parts/about";
import Company from "../components/parts/company";
import Advantages from "../components/parts/advantages";

import Contact from "../components/parts/contact";
import Project from "../components/parts/project";



const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" ></link>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"></link>

      </Head>
      <Nab />

      <Swiper
        direction={"vertical"}
        slidesPerView={1}
        mousewheel={true}
        freeMode={true}
        scrollbar={true}
        parallax={true}
        speed={2000}
        pagination={{ clickable: true, }}
        modules={[FreeMode, Scrollbar, Mousewheel, Pagination]}
        className="mySwiper"
        cssMode={true}
      >
        <SwiperSlide>
          <Banner />
        </SwiperSlide>

        <SwiperSlide>
          <About />
        </SwiperSlide>

        <SwiperSlide>
          <Company />
        </SwiperSlide>

        <SwiperSlide>
          <Advantages />
        </SwiperSlide>

        <SwiperSlide>
          <Project />
        </SwiperSlide>

        <SwiperSlide>
          <Contact />
        </SwiperSlide>
      </Swiper>

    </div>
  );
};

export default Home;
